# Generated by Django 5.1.2 on 2024-10-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('credit_card_number', models.CharField(blank=True, max_length=255)),
                ('valid_thru', models.CharField(blank=True, max_length=5)),
                ('cvv', models.CharField(blank=True, max_length=4)),
                ('card_name', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('VIRTUAL_ACCOUNT', 'Virtual Account')], default='CREDIT_CARD', max_length=255)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=255)),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('credit_card_number', models.CharField(blank=True, max_length=255)),
                ('valid_thru', models.CharField(blank=True, max_length=5)),
                ('cvv', models.CharField(blank=True, max_length=4)),
                ('card_name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Profile',
                'db_table': 'payment_profile',
            },
        ),
    ]
