# Generated by Django 5.1.1 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("VIRTUAL_ACCOUNT", "Virtual Account"),
                    ("CREDIT_CARD", "Credit Card"),
                ],
                default="CREDIT_CARD",
                max_length=255,
            ),
        ),
    ]
