# Generated by Django 5.1.1 on 2024-10-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_payment_method_and_more'),
        ('payment', '0005_alter_transaction_payment_method'),
    ]

    operations = [
    ]
