# Generated by Django 5.1.1 on 2024-10-27 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_merge_20241027_1018"),
        ("payment", "0006_merge_20241027_1716"),
    ]

    operations = []
