# Generated by Django 5.1 on 2024-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Hotel", models.TextField(blank=True, null=True)),
                ("Category", models.TextField(blank=True, null=True)),
                ("Rating", models.FloatField(blank=True, null=True)),
                ("Address", models.TextField(blank=True, null=True)),
                ("Contact", models.TextField(blank=True, null=True)),
                ("Price", models.TextField(blank=True, null=True)),
                ("Amenities", models.TextField(blank=True, null=True)),
                ("Image_URL", models.TextField(blank=True, null=True)),
                ("Location", models.TextField(blank=True, null=True)),
                ("Page_URL", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
