# Generated by Django 5.1 on 2024-10-26 11:43

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "DataHotel.json")

class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
