# Generated by Django 5.1.2 on 2024-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="page_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
