# Generated by Django 5.1.1 on 2024-10-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_proprating_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Rating',
        ),
    ]
